version: "3.9"

services:
  app:
    build: .
    container_name: bibliotheca_app
    restart: unless-stopped
    volumes:
      - ./data:/app/data
    environment:
      - NODE_ENV=production
      - DATABASE_PATH=/app/data/database.sqlite
      - SCHEMA_PATH=/app/src/lib/schema.sql
      - HOSTNAME=0.0.0.0
      - PORT=3000
    networks:
      - webnet

  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
    networks:
      - webnet

networks:
  webnet:
    driver: bridge
